apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553021162727:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T02:46:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1582"
  uid: 398e75d8-2132-469e-b65d-60fc62683cf7
